### 쿠폰 생성 (ADMIN) 성공
POST http://localhost:19098/api/v1/coupons
Content-Type: application/json
X-User-Role: ROLE_ADMIN

{
  "name": "test",
  "discountRate": 10,
  "quantity": 2
}

### 쿠폰 생성 (USER) 실패
POST http://localhost:19098/api/v1/coupons
Content-Type: application/json
X-User-Role: ROLE_USER

{
  "name": "test1",
  "discountRate": 10,
  "quantity": 1
}

### 쿠폰 단일 조회
GET http://localhost:19098/api/v1/coupons/dfad90d9-46d1-4eb0-9c2a-01dc9e4a56d2
Content-Type: application/json
